version: '3'

volumes:
  i2b2-db:

services:
  i2b2-proxy:
    container_name:
      i2b2.proxy
    # image: ${IMAGE_NAMESPACE}/i2b2/i2b2-proxy:${APP_VERSION}
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - i2b2-web

  i2b2-web:
    container_name:
      i2b2.web
    image: ${IMAGE_NAMESPACE}/i2b2/i2b2-web:${APP_VERSION}
    # build:
    #   context: ./web
    #   dockerfile: Dockerfile
    #   args:
    #     WEB_TAG: ${WEB_TAG}
    env_file:
      - .env
    depends_on:
      - i2b2-wildfly

  i2b2-wildfly:
    container_name:
      i2b2.wildfly
    image: ${IMAGE_NAMESPACE}/i2b2/i2b2-wildfly:${APP_VERSION}
    # build:
    #   context: ./wildfly
    #   dockerfile: Dockerfile
    #   args:
    #     WILDFLY_TAG: ${WILDFLY_TAG}
    env_file:
      - .env
      - .env-secrets
    depends_on:
      - i2b2-database

  i2b2-database:
    container_name:
      i2b2.database
    image: ${IMAGE_NAMESPACE}/i2b2/i2b2-database:${APP_VERSION}
    # build:
    #   context: ./database
    #   dockerfile: Dockerfile.postgres
    volumes:
      - i2b2-db:/var/lib/postgresql/data
    env_file:
      - .env
      - .env-secrets

  i2b2-api:
    container_name:
      i2b2.api
    # image: ${IMAGE_NAMESPACE}/i2b2/i2b2-api:${APP_VERSION}
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    ## DEBUG command
    # entrypoint:
    #   tail -F nothing
    depends_on:
      - i2b2-database

  i2b2-meta:
    container_name:
      i2b2.meta
    image: ${IMAGE_NAMESPACE}/i2b2/i2b2-meta:${APP_VERSION}
    # build:
    #   context: ./meta-java
    #   # context: ./meta-python
    #   dockerfile: Dockerfile
    ## Attempt to limit resources - not well implemented for docker compose!
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 50M
    env_file:
      - .env
      - .env-secrets
    ## DEBUG command
    # command:
    #   tail -F nothing
    depends_on:
      - i2b2-database
